filter:
    paths:
        - src/
    excluded_paths:
        - config/
        - tests/
    dependency_paths:
        - vendor/
build:
    environment:
        php: 7.2.13
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
                    - phpcs-run
tools:
    external_code_coverage: true