language: php
sudo: false
cache: composer

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - hhvm-nightly

matrix:
 include:
    - php: 5.4
      env: dependencies=lowest
    - php: 5.5
      env: dependencies=lowest
    - php: 5.6
      env: dependencies=lowest
    - php: 7
      env: dependencies=lowest
    - php: hhvm
      env: dependencies=lowest
    - php: hhvm-nightly
      env: dependencies=lowest
  allow_failures:
    - php: 7
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - composer self-update
  - composer install
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script: make travis

notifications:
  webhooks:
    urls:
      - http://wyrihaximus.net/wyri_projects/wyri_projects/webhook/travisci.json
    on_success: always
    on_failure: always
    on_start: true
